### ISSUE TITLE
Add option to give the root-dir of the kasse-source

### ISSUE THREAD

**Issue by tynsh** [nnev/kasse#40]
Currently there is an option to specify the location of the database, but not of the template-dir. I think it would be nice to have an option to specify both at the same time.

For example: `kasse -basedir=$HOME/go/src/github.com/nnev/kasse`

**Comment by Merovius** [comment]
I don't consider this useful for the intended usecase. Just run the binary in the appropriate directory (it is started by a service anyway).

I'm not violently opposed to the idea, but it seems unnecessary to me and unnecessary features are called "bloat" :)
